# Netlify configuration for Couple Hashtag Maker

[build]
  # Base directory for the build
  base = "frontend"
  
  # Command to build the site
  command = "npm run build"
  
  # Directory with the production-ready files
  publish = "build"

# Environment variables (set these in Netlify dashboard)
# REACT_APP_API_URL = your backend URL (if using separate backend)

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
