import React from 'react';
import { Link } from 'react-router-dom';
import './FooterPages.css';

const TermsOfUse = () => {
  return (
    <div className="footer-page">
      <div className="footer-page-content">
        <h1>Terms of Use</h1>
        <p className="lead">Last updated: {new Date().toLocaleDateString()}</p>
        
        <section className="page-section">
          <h2>1. Acceptance of Terms</h2>
          <p>
            By accessing and using Couple Hashtag Maker, you accept and agree to be bound by the terms 
            and provision of this agreement. If you do not agree to these terms, please do not use our service.
          </p>
        </section>

        <section className="page-section">
          <h2>2. Use of Service</h2>
          <p>
            Our service is provided free of charge for personal, non-commercial use. You may use the 
            generated hashtags for your personal social media posts, wedding invitations, and other 
            personal purposes.
          </p>
        </section>

        <section className="page-section">
          <h2>3. User Responsibilities</h2>
          <ul className="terms-list">
            <li>You are responsible for the names you enter into our system</li>
            <li>You agree not to use offensive, harmful, or inappropriate names</li>
            <li>You will not attempt to abuse, disrupt, or compromise our service</li>
            <li>You will not use automated tools to generate hashtags in bulk</li>
          </ul>
        </section>

        <section className="page-section">
          <h2>4. Intellectual Property</h2>
          <p>
            The hashtags generated by our tool are freely available for your use. However, the website 
            design, code, and algorithms are protected by copyright and may not be reproduced without permission.
          </p>
        </section>

        <section className="page-section">
          <h2>5. Disclaimer</h2>
          <p>
            We provide this service "as is" without any warranties. We do not guarantee that all 
            generated hashtags will be unique or available on social media platforms. Users should 
            verify hashtag availability before use.
          </p>
        </section>

        <section className="page-section">
          <h2>6. Limitation of Liability</h2>
          <p>
            Couple Hashtag Maker shall not be liable for any indirect, incidental, special, consequential, 
            or punitive damages resulting from your use of or inability to use the service.
          </p>
        </section>

        <section className="page-section">
          <h2>7. Changes to Terms</h2>
          <p>
            We reserve the right to modify these terms at any time. Continued use of the service after 
            changes constitutes acceptance of the modified terms.
          </p>
        </section>

        <section className="page-section">
          <h2>8. Contact</h2>
          <p>
            If you have any questions about these Terms of Use, please contact us through our website.
          </p>
        </section>

        <div className="back-link">
          <Link to="/">← Back to Home</Link>
        </div>
      </div>
    </div>
  );
};

export default TermsOfUse;
